// Generated by tools/generate_walls.py. Do not edit manually.
// Source layout: stages/stage_3_small.bmp

#ifndef STAGE_3_DEFS_H
#define STAGE_3_DEFS_H

#include <array>

#include "walls.h"

namespace stage_3_defs
{
    constexpr inline std::array<wall_data, 10> horizontal_walls = {
        wall_data{ bn::fixed_point(0, 48), bn::fixed_point(208, 48) },
        wall_data{ bn::fixed_point(304, 48), bn::fixed_point(608, 48) },
        wall_data{ bn::fixed_point(0, 96), bn::fixed_point(32, 96) },
        wall_data{ bn::fixed_point(520, 96), bn::fixed_point(608, 96) },
        wall_data{ bn::fixed_point(352, 104), bn::fixed_point(464, 104) },
        wall_data{ bn::fixed_point(352, 184), bn::fixed_point(464, 184) },
        wall_data{ bn::fixed_point(208, 232), bn::fixed_point(304, 232) },
        wall_data{ bn::fixed_point(352, 232), bn::fixed_point(520, 232) },
        wall_data{ bn::fixed_point(32, 280), bn::fixed_point(232, 280) },
        wall_data{ bn::fixed_point(232, 392), bn::fixed_point(352, 392) },
    };

    constexpr inline std::array<wall_data, 14> vertical_walls = {
        wall_data{ bn::fixed_point(0, 48), bn::fixed_point(0, 96) },
        wall_data{ bn::fixed_point(32, 96), bn::fixed_point(32, 280) },
        wall_data{ bn::fixed_point(80, 96), bn::fixed_point(80, 232) },
        wall_data{ bn::fixed_point(120, 96), bn::fixed_point(120, 232) },
        wall_data{ bn::fixed_point(160, 96), bn::fixed_point(160, 232) },
        wall_data{ bn::fixed_point(208, 48), bn::fixed_point(208, 232) },
        wall_data{ bn::fixed_point(232, 280), bn::fixed_point(232, 392) },
        wall_data{ bn::fixed_point(304, 48), bn::fixed_point(304, 232) },
        wall_data{ bn::fixed_point(304, 288), bn::fixed_point(304, 344) },
        wall_data{ bn::fixed_point(352, 104), bn::fixed_point(352, 144) },
        wall_data{ bn::fixed_point(352, 232), bn::fixed_point(352, 392) },
        wall_data{ bn::fixed_point(464, 144), bn::fixed_point(464, 184) },
        wall_data{ bn::fixed_point(520, 96), bn::fixed_point(520, 232) },
        wall_data{ bn::fixed_point(608, 48), bn::fixed_point(608, 96) },
    };

}

#endif
