// Generated by tools/generate_walls.py. Do not edit manually.
// Source layout: stages/stage_5_small.bmp

#ifndef STAGE_5_DEFS_H
#define STAGE_5_DEFS_H

#include <array>

#include "walls.h"

namespace stage_5_defs
{
    constexpr inline std::array<wall_data, 28> horizontal_walls = {
        wall_data{ bn::fixed_point(456, 56), bn::fixed_point(512, 56) },
        wall_data{ bn::fixed_point(192, 120), bn::fixed_point(408, 120) },
        wall_data{ bn::fixed_point(560, 120), bn::fixed_point(752, 120) },
        wall_data{ bn::fixed_point(264, 168), bn::fixed_point(368, 168) },
        wall_data{ bn::fixed_point(408, 168), bn::fixed_point(456, 168) },
        wall_data{ bn::fixed_point(512, 168), bn::fixed_point(560, 168) },
        wall_data{ bn::fixed_point(600, 168), bn::fixed_point(664, 168) },
        wall_data{ bn::fixed_point(192, 200), bn::fixed_point(232, 200) },
        wall_data{ bn::fixed_point(376, 216), bn::fixed_point(592, 216) },
        wall_data{ bn::fixed_point(752, 216), bn::fixed_point(848, 216) },
        wall_data{ bn::fixed_point(264, 232), bn::fixed_point(304, 232) },
        wall_data{ bn::fixed_point(664, 256), bn::fixed_point(792, 256) },
        wall_data{ bn::fixed_point(192, 264), bn::fixed_point(232, 264) },
        wall_data{ bn::fixed_point(456, 288), bn::fixed_point(512, 288) },
        wall_data{ bn::fixed_point(264, 296), bn::fixed_point(304, 296) },
        wall_data{ bn::fixed_point(192, 328), bn::fixed_point(232, 328) },
        wall_data{ bn::fixed_point(376, 352), bn::fixed_point(456, 352) },
        wall_data{ bn::fixed_point(512, 352), bn::fixed_point(592, 352) },
        wall_data{ bn::fixed_point(232, 376), bn::fixed_point(304, 376) },
        wall_data{ bn::fixed_point(304, 408), bn::fixed_point(392, 408) },
        wall_data{ bn::fixed_point(432, 408), bn::fixed_point(544, 408) },
        wall_data{ bn::fixed_point(584, 408), bn::fixed_point(664, 408) },
        wall_data{ bn::fixed_point(664, 448), bn::fixed_point(808, 448) },
        wall_data{ bn::fixed_point(232, 480), bn::fixed_point(344, 480) },
        wall_data{ bn::fixed_point(344, 536), bn::fixed_point(440, 536) },
        wall_data{ bn::fixed_point(480, 552), bn::fixed_point(664, 552) },
        wall_data{ bn::fixed_point(192, 592), bn::fixed_point(480, 592) },
        wall_data{ bn::fixed_point(664, 600), bn::fixed_point(848, 600) },
    };

    constexpr inline std::array<wall_data, 23> vertical_walls = {
        wall_data{ bn::fixed_point(192, 120), bn::fixed_point(192, 592) },
        wall_data{ bn::fixed_point(232, 376), bn::fixed_point(232, 424) },
        wall_data{ bn::fixed_point(304, 168), bn::fixed_point(304, 312) },
        wall_data{ bn::fixed_point(304, 352), bn::fixed_point(304, 408) },
        wall_data{ bn::fixed_point(344, 408), bn::fixed_point(344, 440) },
        wall_data{ bn::fixed_point(344, 480), bn::fixed_point(344, 536) },
        wall_data{ bn::fixed_point(376, 216), bn::fixed_point(376, 352) },
        wall_data{ bn::fixed_point(408, 120), bn::fixed_point(408, 168) },
        wall_data{ bn::fixed_point(456, 56), bn::fixed_point(456, 168) },
        wall_data{ bn::fixed_point(456, 288), bn::fixed_point(456, 352) },
        wall_data{ bn::fixed_point(480, 408), bn::fixed_point(480, 592) },
        wall_data{ bn::fixed_point(512, 56), bn::fixed_point(512, 168) },
        wall_data{ bn::fixed_point(512, 288), bn::fixed_point(512, 352) },
        wall_data{ bn::fixed_point(560, 120), bn::fixed_point(560, 168) },
        wall_data{ bn::fixed_point(592, 216), bn::fixed_point(592, 352) },
        wall_data{ bn::fixed_point(664, 168), bn::fixed_point(664, 216) },
        wall_data{ bn::fixed_point(664, 256), bn::fixed_point(664, 408) },
        wall_data{ bn::fixed_point(664, 448), bn::fixed_point(664, 496) },
        wall_data{ bn::fixed_point(664, 536), bn::fixed_point(664, 600) },
        wall_data{ bn::fixed_point(720, 296), bn::fixed_point(720, 344) },
        wall_data{ bn::fixed_point(752, 120), bn::fixed_point(752, 216) },
        wall_data{ bn::fixed_point(792, 360), bn::fixed_point(792, 408) },
        wall_data{ bn::fixed_point(848, 216), bn::fixed_point(848, 600) },
    };

}

#endif
