// Generated by tools/generate_walls.py. Do not edit manually.
// Source layout: stages/stage_1_small.bmp

#ifndef STAGE_1_DEFS_H
#define STAGE_1_DEFS_H

#include <array>

#include "walls.h"

namespace stage_1_defs
{
    constexpr inline std::array<wall_data, 8> horizontal_walls = {
        wall_data{ bn::fixed_point(544, 24), bn::fixed_point(600, 24) },
        wall_data{ bn::fixed_point(376, 328), bn::fixed_point(544, 328) },
        wall_data{ bn::fixed_point(448, 400), bn::fixed_point(528, 400) },
        wall_data{ bn::fixed_point(88, 456), bn::fixed_point(376, 456) },
        wall_data{ bn::fixed_point(200, 536), bn::fixed_point(376, 536) },
        wall_data{ bn::fixed_point(448, 544), bn::fixed_point(528, 544) },
        wall_data{ bn::fixed_point(376, 616), bn::fixed_point(600, 616) },
        wall_data{ bn::fixed_point(88, 920), bn::fixed_point(200, 920) },
    };

    constexpr inline std::array<wall_data, 8> vertical_walls = {
        wall_data{ bn::fixed_point(88, 456), bn::fixed_point(88, 920) },
        wall_data{ bn::fixed_point(200, 536), bn::fixed_point(200, 920) },
        wall_data{ bn::fixed_point(376, 328), bn::fixed_point(376, 456) },
        wall_data{ bn::fixed_point(376, 536), bn::fixed_point(376, 616) },
        wall_data{ bn::fixed_point(448, 400), bn::fixed_point(448, 544) },
        wall_data{ bn::fixed_point(528, 400), bn::fixed_point(528, 544) },
        wall_data{ bn::fixed_point(544, 24), bn::fixed_point(544, 328) },
        wall_data{ bn::fixed_point(600, 24), bn::fixed_point(600, 616) },
    };

}

#endif
