// Generated by tools/generate_walls.py. Do not edit manually.
// Source layout: stages/stage_4_small.bmp

#ifndef STAGE_4_DEFS_H
#define STAGE_4_DEFS_H

#include <array>

#include "walls.h"

namespace stage_4_defs
{
    constexpr inline std::array<wall_data, 16> horizontal_walls = {
        wall_data{ bn::fixed_point(80, 48), bn::fixed_point(328, 48) },
        wall_data{ bn::fixed_point(128, 96), bn::fixed_point(184, 96) },
        wall_data{ bn::fixed_point(248, 96), bn::fixed_point(280, 96) },
        wall_data{ bn::fixed_point(328, 120), bn::fixed_point(416, 120) },
        wall_data{ bn::fixed_point(184, 152), bn::fixed_point(208, 152) },
        wall_data{ bn::fixed_point(320, 160), bn::fixed_point(368, 160) },
        wall_data{ bn::fixed_point(320, 184), bn::fixed_point(368, 184) },
        wall_data{ bn::fixed_point(176, 216), bn::fixed_point(248, 216) },
        wall_data{ bn::fixed_point(280, 224), bn::fixed_point(368, 224) },
        wall_data{ bn::fixed_point(24, 232), bn::fixed_point(80, 232) },
        wall_data{ bn::fixed_point(264, 264), bn::fixed_point(368, 264) },
        wall_data{ bn::fixed_point(24, 280), bn::fixed_point(208, 280) },
        wall_data{ bn::fixed_point(312, 304), bn::fixed_point(368, 304) },
        wall_data{ bn::fixed_point(312, 328), bn::fixed_point(368, 328) },
        wall_data{ bn::fixed_point(312, 368), bn::fixed_point(416, 368) },
        wall_data{ bn::fixed_point(264, 440), bn::fixed_point(312, 440) },
    };

    constexpr inline std::array<wall_data, 16> vertical_walls = {
        wall_data{ bn::fixed_point(24, 232), bn::fixed_point(24, 280) },
        wall_data{ bn::fixed_point(80, 48), bn::fixed_point(80, 232) },
        wall_data{ bn::fixed_point(128, 96), bn::fixed_point(128, 216) },
        wall_data{ bn::fixed_point(184, 96), bn::fixed_point(184, 152) },
        wall_data{ bn::fixed_point(208, 216), bn::fixed_point(208, 280) },
        wall_data{ bn::fixed_point(248, 96), bn::fixed_point(248, 216) },
        wall_data{ bn::fixed_point(264, 264), bn::fixed_point(264, 440) },
        wall_data{ bn::fixed_point(280, 96), bn::fixed_point(280, 224) },
        wall_data{ bn::fixed_point(312, 304), bn::fixed_point(312, 328) },
        wall_data{ bn::fixed_point(312, 368), bn::fixed_point(312, 440) },
        wall_data{ bn::fixed_point(320, 160), bn::fixed_point(320, 184) },
        wall_data{ bn::fixed_point(328, 48), bn::fixed_point(328, 120) },
        wall_data{ bn::fixed_point(368, 160), bn::fixed_point(368, 184) },
        wall_data{ bn::fixed_point(368, 224), bn::fixed_point(368, 264) },
        wall_data{ bn::fixed_point(368, 304), bn::fixed_point(368, 328) },
        wall_data{ bn::fixed_point(416, 120), bn::fixed_point(416, 368) },
    };

}

#endif
