// Generated by tools/generate_walls.py. Do not edit manually.
// Source layout: stages/stage_2_small.bmp

#ifndef STAGE_2_DEFS_H
#define STAGE_2_DEFS_H

#include <array>

#include "walls.h"

namespace stage_2_defs
{
    constexpr inline std::array<wall_data, 9> horizontal_walls = {
        wall_data{ bn::fixed_point(88, 40), bn::fixed_point(152, 40) },
        wall_data{ bn::fixed_point(152, 128), bn::fixed_point(416, 128) },
        wall_data{ bn::fixed_point(192, 232), bn::fixed_point(376, 232) },
        wall_data{ bn::fixed_point(416, 232), bn::fixed_point(512, 232) },
        wall_data{ bn::fixed_point(88, 280), bn::fixed_point(176, 280) },
        wall_data{ bn::fixed_point(224, 280), bn::fixed_point(296, 280) },
        wall_data{ bn::fixed_point(344, 280), bn::fixed_point(512, 280) },
        wall_data{ bn::fixed_point(128, 360), bn::fixed_point(248, 360) },
        wall_data{ bn::fixed_point(88, 432), bn::fixed_point(416, 432) },
    };

    constexpr inline std::array<wall_data, 6> vertical_walls = {
        wall_data{ bn::fixed_point(88, 40), bn::fixed_point(88, 432) },
        wall_data{ bn::fixed_point(152, 40), bn::fixed_point(152, 232) },
        wall_data{ bn::fixed_point(248, 280), bn::fixed_point(248, 392) },
        wall_data{ bn::fixed_point(416, 128), bn::fixed_point(416, 232) },
        wall_data{ bn::fixed_point(416, 280), bn::fixed_point(416, 432) },
        wall_data{ bn::fixed_point(512, 232), bn::fixed_point(512, 280) },
    };

}

#endif
